CREATE TABLE [dbo].[FlareUps]
(
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT newid(), 
    [ExperiencedOn] DATETIME2 NOT NULL, 
    [UserID] UNIQUEIDENTIFIER NOT NULL, 
    [SymptomID] UNIQUEIDENTIFIER NOT NULL, 
    [Severity] FLOAT NOT NULL
)
